version: '3'
services:
  # web:
  #   image: nginx
  #   volumes:
  #     - ./default-conf.template:/etc/nginx/conf.d/default-conf.template
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - NGINX_HOST=foobar.com
  #     - NGINX_PORT=80
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default-conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  aggregator:
    build: images/fluentd-cloud-logging
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./credentials.json:/fluentd/etc/credentials.json
    ports:
      - "9880:9880"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/fluentd/etc/credentials.json

